[project]
name = "strats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["posetree>=1.1.2"]

[tool.pyright]
venvPath = "."
venv = ".venv"
