[project]
name = "pico"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "micropython-rp2-rpi-pico2-stubs>=1.25.0.post1",
]
